### ISSUE TITLE
Space key triggers both close and open

### ISSUE THREAD

**Issue by patrickcate** [jsor/ctrly#5]
When pressing the space key it seems like it is trigger both a close and open event. You can see it in the accordion demo: https://sorgalla.com/ctrly/examples/accordion/

![ctrly](https://user-images.githubusercontent.com/6277206/69468690-1bee2b80-0d5b-11ea-8313-b5f561936aed.gif)

**Comment by jsor** [comment]
Thanks for the report, which Browser and Version of it are you using?

**Comment by patrickcate** [comment]
I've tested it on the following browsers:

1. Chrome 78
1. Firefox 70
1. Safari 12.1.12

**Comment by jsor** [comment]
I think i [fixed](https://github.com/jsor/ctrly/commit/794603165f9bc7fccbdd5334e05b9c9a6356a213#diff-2ffca25c6ffe1fe29f8bcf232723c8bfR561) it. It would be great if you could test it from the [`dist/`](https://github.com/jsor/ctrly/tree/794603165f9bc7fccbdd5334e05b9c9a6356a213/dist) and verify it is also fixed for you.

**Comment by patrickcate** [comment]
> I think i fixed it. It would be great if you could test it from the dist/ and verify it is also fixed for you.

I just tested and I can confirm the issue is fixed.

**Comment by jsor** [comment]
Thanks for the feedback! Fix released in [v0.7.0](https://github.com/jsor/ctrly/releases/tag/v0.7.0).
